# US West region   : PIMS_DOCKER_1.6.0_AMI='ami-59989f69' | PIMS_DOCKER_1.7.0_AMI='ami-fdd5d2cd' | AWS_UBUNTU_AMI='ami-a3c59393' ~> Ubuntu 14.10
# EU Ireland region: PIMS_DOCKER_1.6.0_AMI='ami-1480c263'
aws:
  box: dummy
  box_url: https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box
  access_key_id: AKIAIXRPYHKAPB5P3DHA
  vpc_id: vpc-0606ec63
  secret_access_key: cAU7gi2byWee/pcQ50DeOIGG/ABkX1O9qn57NYYS
  keypair_name: turbo-aws


  development:
    name: Metadata
    hostname: turbo.metadata
    instance_type: c3.2xlarge
    ami: 'ami-06116566'
    region: us-west-1
    elastic_ip: 52.24.86.21â€¨
    domain: turbo-metadata.zoral.com.ua
    security_group: development



